#include "d3d11_converters.h"

#include <assert.h>

D3D11_USAGE d_usage(d3_usage usage) {
    switch (usage) {
    case D3_USAGE_IMMUTABLE: return D3D11_USAGE_IMMUTABLE;
    case D3_USAGE_DYNAMIC:
    case D3_USAGE_STREAM: return D3D11_USAGE_DYNAMIC;
    default: assert(false); return (D3D11_USAGE)0;
    }
}

UINT d_cpu_access_flags(d3_usage usage) {
    switch (usage) {
    case D3_USAGE_IMMUTABLE: return 0;
    case D3_USAGE_DYNAMIC:
    case D3_USAGE_STREAM: return D3D11_CPU_ACCESS_WRITE;
    default: assert(false); return 0;
    }
}

DXGI_FORMAT d_pixel_format(d3_pixel_format format) {
    switch (format) {
    case D3_PIXELFORMAT_R8: return DXGI_FORMAT_R8_UNORM;
    case D3_PIXELFORMAT_R8SN: return DXGI_FORMAT_R8_SNORM;
    case D3_PIXELFORMAT_R8UI: return DXGI_FORMAT_R8_UINT;
    case D3_PIXELFORMAT_R8SI: return DXGI_FORMAT_R8_SINT;
    case D3_PIXELFORMAT_R16: return DXGI_FORMAT_R16_UNORM;
    case D3_PIXELFORMAT_R16SN: return DXGI_FORMAT_R16_SNORM;
    case D3_PIXELFORMAT_R16UI: return DXGI_FORMAT_R16_UINT;
    case D3_PIXELFORMAT_R16SI: return DXGI_FORMAT_R16_SINT;
    case D3_PIXELFORMAT_R16F: return DXGI_FORMAT_R16_FLOAT;
    case D3_PIXELFORMAT_RG8: return DXGI_FORMAT_R8G8_UNORM;
    case D3_PIXELFORMAT_RG8SN: return DXGI_FORMAT_R8G8_SNORM;
    case D3_PIXELFORMAT_RG8UI: return DXGI_FORMAT_R8G8_UINT;
    case D3_PIXELFORMAT_RG8SI: return DXGI_FORMAT_R8G8_SINT;
    case D3_PIXELFORMAT_R32UI: return DXGI_FORMAT_R32_UINT;
    case D3_PIXELFORMAT_R32SI: return DXGI_FORMAT_R32_SINT;
    case D3_PIXELFORMAT_R32F: return DXGI_FORMAT_R32_FLOAT;
    case D3_PIXELFORMAT_RG16: return DXGI_FORMAT_R16G16_UNORM;
    case D3_PIXELFORMAT_RG16SN: return DXGI_FORMAT_R16G16_SNORM;
    case D3_PIXELFORMAT_RG16UI: return DXGI_FORMAT_R16G16_UINT;
    case D3_PIXELFORMAT_RG16SI: return DXGI_FORMAT_R16G16_SINT;
    case D3_PIXELFORMAT_RG16F: return DXGI_FORMAT_R16G16_FLOAT;
    case D3_PIXELFORMAT_RGBA8: return DXGI_FORMAT_R8G8B8A8_UNORM;
    case D3_PIXELFORMAT_RGBA8SN: return DXGI_FORMAT_R8G8B8A8_SNORM;
    case D3_PIXELFORMAT_RGBA8UI: return DXGI_FORMAT_R8G8B8A8_UINT;
    case D3_PIXELFORMAT_RGBA8SI: return DXGI_FORMAT_R8G8B8A8_SINT;
    case D3_PIXELFORMAT_BGRA8: return DXGI_FORMAT_B8G8R8A8_UNORM;
    case D3_PIXELFORMAT_RGB10A2: return DXGI_FORMAT_R10G10B10A2_UNORM;
    case D3_PIXELFORMAT_RG11B10F: return DXGI_FORMAT_R11G11B10_FLOAT;
    case D3_PIXELFORMAT_RG32UI: return DXGI_FORMAT_R32G32_UINT;
    case D3_PIXELFORMAT_RG32SI: return DXGI_FORMAT_R32G32_SINT;
    case D3_PIXELFORMAT_RG32F: return DXGI_FORMAT_R32G32_FLOAT;
    case D3_PIXELFORMAT_RGBA16: return DXGI_FORMAT_R16G16B16A16_UNORM;
    case D3_PIXELFORMAT_RGBA16SN: return DXGI_FORMAT_R16G16B16A16_SNORM;
    case D3_PIXELFORMAT_RGBA16UI: return DXGI_FORMAT_R16G16B16A16_UINT;
    case D3_PIXELFORMAT_RGBA16SI: return DXGI_FORMAT_R16G16B16A16_SINT;
    case D3_PIXELFORMAT_RGBA16F: return DXGI_FORMAT_R16G16B16A16_FLOAT;
    case D3_PIXELFORMAT_RGBA32UI: return DXGI_FORMAT_R32G32B32A32_UINT;
    case D3_PIXELFORMAT_RGBA32SI: return DXGI_FORMAT_R32G32B32A32_SINT;
    case D3_PIXELFORMAT_RGBA32F: return DXGI_FORMAT_R32G32B32A32_FLOAT;
    case D3_PIXELFORMAT_DEPTH: return DXGI_FORMAT_D32_FLOAT;
    case D3_PIXELFORMAT_DEPTH_STENCIL: return DXGI_FORMAT_D24_UNORM_S8_UINT;
    case D3_PIXELFORMAT_BC1_RGBA: return DXGI_FORMAT_BC1_UNORM;
    case D3_PIXELFORMAT_BC2_RGBA: return DXGI_FORMAT_BC2_UNORM;
    case D3_PIXELFORMAT_BC3_RGBA: return DXGI_FORMAT_BC3_UNORM;
    case D3_PIXELFORMAT_BC4_R: return DXGI_FORMAT_BC4_UNORM;
    case D3_PIXELFORMAT_BC4_RSN: return DXGI_FORMAT_BC4_SNORM;
    case D3_PIXELFORMAT_BC5_RG: return DXGI_FORMAT_BC5_UNORM;
    case D3_PIXELFORMAT_BC5_RGSN: return DXGI_FORMAT_BC5_SNORM;
    case D3_PIXELFORMAT_BC6H_RGBF: return DXGI_FORMAT_BC6H_SF16;
    case D3_PIXELFORMAT_BC6H_RGBUF: return DXGI_FORMAT_BC6H_UF16;
    case D3_PIXELFORMAT_BC7_RGBA: return DXGI_FORMAT_BC7_UNORM;
    default: return DXGI_FORMAT_UNKNOWN;
    };
}

D3D11_PRIMITIVE_TOPOLOGY d_primitive_topology(d3_primitive_type prim_type) {
    switch (prim_type) {
    case D3_PRIMITIVETYPE_POINTS: return D3D11_PRIMITIVE_TOPOLOGY_POINTLIST;
    case D3_PRIMITIVETYPE_LINES: return D3D11_PRIMITIVE_TOPOLOGY_LINELIST;
    case D3_PRIMITIVETYPE_LINE_STRIP: return D3D11_PRIMITIVE_TOPOLOGY_LINESTRIP;
    case D3_PRIMITIVETYPE_TRIANGLES: return D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST;
    case D3_PRIMITIVETYPE_TRIANGLE_STRIP: return D3D11_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP;
    default: assert(false); return (D3D11_PRIMITIVE_TOPOLOGY)0;
    }
}

DXGI_FORMAT d_index_format(d3_index_type index_type) {
    switch (index_type) {
    case D3_INDEXTYPE_NONE: return DXGI_FORMAT_UNKNOWN;
    case D3_INDEXTYPE_UINT16: return DXGI_FORMAT_R16_UINT;
    case D3_INDEXTYPE_UINT32: return DXGI_FORMAT_R32_UINT;
    default: assert(false); return (DXGI_FORMAT)0;
    }
}

D3D11_FILTER d_filter(d3_filter min_f, d3_filter mag_f, uint32_t max_anisotropy) {
    if (max_anisotropy > 1) {
        return D3D11_FILTER_ANISOTROPIC;
    } else if (mag_f == D3_FILTER_NEAREST) {
        switch (min_f) {
        case D3_FILTER_NEAREST:
        case D3_FILTER_NEAREST_MIPMAP_NEAREST: return D3D11_FILTER_MIN_MAG_MIP_POINT;
        case D3_FILTER_LINEAR:
        case D3_FILTER_LINEAR_MIPMAP_NEAREST: return D3D11_FILTER_MIN_LINEAR_MAG_MIP_POINT;
        case D3_FILTER_NEAREST_MIPMAP_LINEAR: return D3D11_FILTER_MIN_MAG_POINT_MIP_LINEAR;
        case D3_FILTER_LINEAR_MIPMAP_LINEAR: return D3D11_FILTER_MIN_LINEAR_MAG_POINT_MIP_LINEAR;
        default: assert(false); break;
        }
    } else if (mag_f == D3_FILTER_LINEAR) {
        switch (min_f) {
        case D3_FILTER_NEAREST:
        case D3_FILTER_NEAREST_MIPMAP_NEAREST: return D3D11_FILTER_MIN_POINT_MAG_LINEAR_MIP_POINT;
        case D3_FILTER_LINEAR:
        case D3_FILTER_LINEAR_MIPMAP_NEAREST: return D3D11_FILTER_MIN_MAG_LINEAR_MIP_POINT;
        case D3_FILTER_NEAREST_MIPMAP_LINEAR: return D3D11_FILTER_MIN_POINT_MAG_MIP_LINEAR;
        case D3_FILTER_LINEAR_MIPMAP_LINEAR: return D3D11_FILTER_MIN_MAG_MIP_LINEAR;
        default: assert(false); break;
        }
    }
    assert(false);
    return D3D11_FILTER_MIN_MAG_MIP_POINT;
}

D3D11_TEXTURE_ADDRESS_MODE d_address_mode(d3_wrap m) {
    switch (m) {
    case D3_WRAP_REPEAT: return D3D11_TEXTURE_ADDRESS_WRAP;
    case D3_WRAP_CLAMP_TO_EDGE: return D3D11_TEXTURE_ADDRESS_CLAMP;
    case D3_WRAP_CLAMP_TO_BORDER: return D3D11_TEXTURE_ADDRESS_BORDER;
    case D3_WRAP_MIRRORED_REPEAT: return D3D11_TEXTURE_ADDRESS_MIRROR;
    default: assert(false); return (D3D11_TEXTURE_ADDRESS_MODE)0;
    }
}

DXGI_FORMAT d_vertex_format(d3_vertex_format fmt) {
    switch (fmt) {
    case D3_VERTEXFORMAT_FLOAT: return DXGI_FORMAT_R32_FLOAT;
    case D3_VERTEXFORMAT_FLOAT2: return DXGI_FORMAT_R32G32_FLOAT;
    case D3_VERTEXFORMAT_FLOAT3: return DXGI_FORMAT_R32G32B32_FLOAT;
    case D3_VERTEXFORMAT_FLOAT4: return DXGI_FORMAT_R32G32B32A32_FLOAT;
    case D3_VERTEXFORMAT_BYTE4: return DXGI_FORMAT_R8G8B8A8_SINT;
    case D3_VERTEXFORMAT_BYTE4N: return DXGI_FORMAT_R8G8B8A8_SNORM;
    case D3_VERTEXFORMAT_UBYTE4: return DXGI_FORMAT_R8G8B8A8_UINT;
    case D3_VERTEXFORMAT_UBYTE4N: return DXGI_FORMAT_R8G8B8A8_UNORM;
    case D3_VERTEXFORMAT_SHORT2: return DXGI_FORMAT_R16G16_SINT;
    case D3_VERTEXFORMAT_SHORT2N: return DXGI_FORMAT_R16G16_SNORM;
    case D3_VERTEXFORMAT_USHORT2N: return DXGI_FORMAT_R16G16_UNORM;
    case D3_VERTEXFORMAT_SHORT4: return DXGI_FORMAT_R16G16B16A16_SINT;
    case D3_VERTEXFORMAT_SHORT4N: return DXGI_FORMAT_R16G16B16A16_SNORM;
    case D3_VERTEXFORMAT_USHORT4N: return DXGI_FORMAT_R16G16B16A16_UNORM;
    case D3_VERTEXFORMAT_UINT10_N2: return DXGI_FORMAT_R10G10B10A2_UNORM;
    default: assert(false); return (DXGI_FORMAT)0;
    }
}

D3D11_INPUT_CLASSIFICATION d_input_classification(d3_vertex_step step) {
    switch (step) {
    case D3_VERTEXSTEP_PER_VERTEX: return D3D11_INPUT_PER_VERTEX_DATA;
    case D3_VERTEXSTEP_PER_INSTANCE: return D3D11_INPUT_PER_INSTANCE_DATA;
    default: assert(false); return (D3D11_INPUT_CLASSIFICATION)0;
    }
}

D3D11_CULL_MODE d_cull_mode(d3_cull_mode m) {
    switch (m) {
    case D3_CULLMODE_NONE: return D3D11_CULL_NONE;
    case D3_CULLMODE_FRONT: return D3D11_CULL_FRONT;
    case D3_CULLMODE_BACK: return D3D11_CULL_BACK;
    default: assert(false); return (D3D11_CULL_MODE)0;
    }
}

D3D11_COMPARISON_FUNC d_compare_func(d3_compare_func f) {
    switch (f) {
    case D3_COMPAREFUNC_NEVER: return D3D11_COMPARISON_NEVER;
    case D3_COMPAREFUNC_LESS: return D3D11_COMPARISON_LESS;
    case D3_COMPAREFUNC_EQUAL: return D3D11_COMPARISON_EQUAL;
    case D3_COMPAREFUNC_LESS_EQUAL: return D3D11_COMPARISON_LESS_EQUAL;
    case D3_COMPAREFUNC_GREATER: return D3D11_COMPARISON_GREATER;
    case D3_COMPAREFUNC_NOT_EQUAL: return D3D11_COMPARISON_NOT_EQUAL;
    case D3_COMPAREFUNC_GREATER_EQUAL: return D3D11_COMPARISON_GREATER_EQUAL;
    case D3_COMPAREFUNC_ALWAYS: return D3D11_COMPARISON_ALWAYS;
    default: assert(false); return (D3D11_COMPARISON_FUNC)0;
    }
}

D3D11_STENCIL_OP d_stencil_op(d3_stencil_op op) {
    switch (op) {
    case D3_STENCILOP_KEEP: return D3D11_STENCIL_OP_KEEP;
    case D3_STENCILOP_ZERO: return D3D11_STENCIL_OP_ZERO;
    case D3_STENCILOP_REPLACE: return D3D11_STENCIL_OP_REPLACE;
    case D3_STENCILOP_INCR_CLAMP: return D3D11_STENCIL_OP_INCR_SAT;
    case D3_STENCILOP_DECR_CLAMP: return D3D11_STENCIL_OP_DECR_SAT;
    case D3_STENCILOP_INVERT: return D3D11_STENCIL_OP_INVERT;
    case D3_STENCILOP_INCR_WRAP: return D3D11_STENCIL_OP_INCR;
    case D3_STENCILOP_DECR_WRAP: return D3D11_STENCIL_OP_DECR;
    default: assert(false); return (D3D11_STENCIL_OP)0;
    }
}

D3D11_BLEND d_blend_factor(d3_blend_factor f) {
    switch (f) {
    case D3_BLENDFACTOR_ZERO: return D3D11_BLEND_ZERO;
    case D3_BLENDFACTOR_ONE: return D3D11_BLEND_ONE;
    case D3_BLENDFACTOR_SRC_COLOR: return D3D11_BLEND_SRC_COLOR;
    case D3_BLENDFACTOR_ONE_MINUS_SRC_COLOR: return D3D11_BLEND_INV_SRC_COLOR;
    case D3_BLENDFACTOR_SRC_ALPHA: return D3D11_BLEND_SRC_ALPHA;
    case D3_BLENDFACTOR_ONE_MINUS_SRC_ALPHA: return D3D11_BLEND_INV_SRC_ALPHA;
    case D3_BLENDFACTOR_DST_COLOR: return D3D11_BLEND_DEST_COLOR;
    case D3_BLENDFACTOR_ONE_MINUS_DST_COLOR: return D3D11_BLEND_INV_DEST_COLOR;
    case D3_BLENDFACTOR_DST_ALPHA: return D3D11_BLEND_DEST_ALPHA;
    case D3_BLENDFACTOR_ONE_MINUS_DST_ALPHA: return D3D11_BLEND_INV_DEST_ALPHA;
    case D3_BLENDFACTOR_SRC_ALPHA_SATURATED: return D3D11_BLEND_SRC_ALPHA_SAT;
    case D3_BLENDFACTOR_BLEND_COLOR: return D3D11_BLEND_BLEND_FACTOR;
    case D3_BLENDFACTOR_ONE_MINUS_BLEND_COLOR: return D3D11_BLEND_INV_BLEND_FACTOR;
    case D3_BLENDFACTOR_BLEND_ALPHA: return D3D11_BLEND_BLEND_FACTOR;
    case D3_BLENDFACTOR_ONE_MINUS_BLEND_ALPHA: return D3D11_BLEND_INV_BLEND_FACTOR;
    default: assert(false); return (D3D11_BLEND)0;
    }
}

D3D11_BLEND_OP d_blend_op(d3_blend_op op) {
    switch (op) {
    case D3_BLENDOP_ADD: return D3D11_BLEND_OP_ADD;
    case D3_BLENDOP_SUBTRACT: return D3D11_BLEND_OP_SUBTRACT;
    case D3_BLENDOP_REVERSE_SUBTRACT: return D3D11_BLEND_OP_REV_SUBTRACT;
    default: assert(false); return (D3D11_BLEND_OP)0;
    }
}

UINT8 d_color_write_mask(d3_color_mask m) {
    UINT8 res = 0;
    if (m & D3_COLORMASK_R) {
        res |= D3D11_COLOR_WRITE_ENABLE_RED;
    }
    if (m & D3_COLORMASK_G) {
        res |= D3D11_COLOR_WRITE_ENABLE_GREEN;
    }
    if (m & D3_COLORMASK_B) {
        res |= D3D11_COLOR_WRITE_ENABLE_BLUE;
    }
    if (m & D3_COLORMASK_A) {
        res |= D3D11_COLOR_WRITE_ENABLE_ALPHA;
    }
    return res;
}
